# Write requirements.txt in binary mode, line by line
with open('requirements.txt', 'wb') as f:
    # Write header
    f.write(b'# RISARMS Ecosystem - Unified Requirements with Three Install Commands\n')
    f.write(b'# Location: C:\\Users\\rishi\\Desktop\\RISARMS\\DOCS\\requirements.txt\n')
    f.write(b'#\n')
    f.write(b'# THREE INSTALL COMMANDS:\n')
    f.write(b'# =============================================================================\n')
    f.write(b'\n')
    f.write(b'# COMMAND 1 - EVERYTHING (all packages + all extras from all 6 repos):\n')
    f.write(b'#   pip install -r C:\\Users\\rishi\\Desktop\\RISARMS\\DOCS\\requirements.txt\n')
    f.write(b'\n')
    f.write(b'# COMMAND 2 - EVERYTHING EXCEPT CORE-HOST:\n')
    f.write(b'#   pip install -r C:\\Users\\rishi\\Desktop\\RISARMS\\DOCS\\requirements.txt --exclude=CORE-HOST\n')
    f.write(b'\n')
    f.write(b'# COMMAND 3 - EVERYTHING EXCEPT CORE-CLIENT:\n')
    f.write(b'#   pip install -r C:\\Users\\rishi\\Desktop\\RISARMS\\DOCS\\requirements.txt --exclude=CORE-CLIENT\n')
    f.write(b'\n')
    f.write(b'# NOTE: pip --exclude is not standard. Use one of these methods:\n')
    f.write(b'#   Method 1 - Manual: Copy the relevant section to a temp file and pip install -r temp.txt\n')
    f.write(b'#   Method 2 - Script: Use the helper script below\n')
    f.write(b'#   Method 3 - Manual install: Copy/paste the relevant section\n')
    f.write(b'\n')
    f.write(b'# HELPER SCRIPT (save as install.py and run: python install.py [all|no-host|no-client]):\n')
    f.write(b'# import sys, re\n')
    f.write(b'# section = sys.argv[1] if len(sys.argv) > 1 else "all"\n')
    f.write(b'# with open(__file__) as f: content = f.read()\n')
    f.write(b'# section_content = re.search(f"# SECTION: {re.escape(section)}(.*?)(?=# SECTION:|$)", content, re.DOTALL)\n')
    f.write(b'# if section_content:\n')
    f.write(b'#     lines = [l for l in section_content.group(1).split("\n") if l and not l.startswith("#")]\n')
    f.write(b'#     with open("temp_req.txt", "w") as f: f.write("\\n".join(lines))\n')
    f.write(b'#     print(f"Created temp_req.txt for section: {section}")\n')
    f.write(b'#     print("Run: pip install -r temp_req.txt")\n')
    f.write(b'\n')
    f.write(b'# =============================================================================\n')
    f.write(b'\n')
    f.write(b'# SECTION: all\n')
    f.write(b'# =============================================================================\n')
    f.write(b'# CORE RUNTIME - All projects\n')
    f.write(b'platformdirs>=4\n')
    f.write(b'python-dotenv>=1.0\n')
    f.write(b'sympy>=1.13\n')
    f.write(b'requests>=2.31\n')
    f.write(b'windows-curses>=2.3; sys_platform == "win32"\n')
    f.write(b'PyYAML>=6.0\n')
    f.write(b'fastapi==0.141.1\n')
    f.write(b'uvicorn[standard]==0.52.4\n')
    f.write(b'sqlalchemy==2.0.52\n')
    f.write(b'psycopg[binary]==3.3.4\n')
    f.write(b'pydantic==2.13.5\n')
    f.write(b'pydantic-settings==2.15.0\n')
    f.write(b'python-multipart==0.0.32\n')
    f.write(b'\n')
    f.write(b'# EXTRAS - All optional dependencies from all projects\n')
    f.write(b'textual>=0.70\n')
    f.write(b'textual-dev>=0.70\n')
    f.write(b'numpy\n')
    f.write(b'scipy\n')
    f.write(b'sounddevice\n')
    f.write(b'soundfile\n')
    f.write(b'silero-vad\n')
    f.write(b'faster-whisper\n')
    f.write(b'torch\n')
    f.write(b'torchaudio\n')
    f.write(b'speechbrain\n')
    f.write(b'openwakeword\n')
    f.write(b'pyttsx3\n')
    f.write(b'pycaw; sys_platform == "win32"\n')
    f.write(b'comtypes; sys_platform == "win32"\n')
    f.write(b'pywin32; sys_platform == "win32"\n')
    f.write(b'pypdf>=4\n')
    f.write(b'python-docx>=1.1\n')
    f.write(b'boto3>=1.28\n')
    f.write(b'\n')
    f.write(b'# DEVELOPMENT / TEST DEPENDENCIES\n')
    f.write(b'pytest>=8\n')
    f.write(b'pytest-cov>=5\n')
    f.write(b'pytest-asyncio>=0.23\n')
    f.write(b'httpx==0.28.1\n')
    f.write(b'ruff\n')
    f.write(b'black\n')
    f.write(b'\n')
    f.write(b'# SECTION: except-core-host\n')
    f.write(b'# =============================================================================\n')
    f.write(b'# CORE RUNTIME - EXCEPT CORE-HOST (excludes PyYAML and fastapi stack)\n')
    f.write(b'platformdirs>=4\n')
    f.write(b'python-dotenv>=1.0\n')
    f.write(b'sympy>=1.13\n')
    f.write(b'requests>=2.31\n')
    f.write(b'windows-curses>=2.3; sys_platform == "win32"\n')
    f.write(b'# PyYAML>=6.0  <-- EXCLUDED (core-host)\n')
    f.write(b'# fastapi==0.141.1  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# uvicorn[standard]==0.52.4  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# sqlalchemy==2.0.52  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# psycopg[binary]==3.3.4  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# pydantic==2.13.5  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# pydantic-settings==2.15.0  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# python-multipart==0.0.32  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'\n')
    f.write(b'# EXTRAS - All optional (same as all)\n')
    f.write(b'textual>=0.70\n')
    f.write(b'textual-dev>=0.70\n')
    f.write(b'numpy\n')
    f.write(b'scipy\n')
    f.write(b'sounddevice\n')
    f.write(b'soundfile\n')
    f.write(b'silero-vad\n')
    f.write(b'faster-whisper\n')
    f.write(b'torch\n')
    f.write(b'torchaudio\n')
    f.write(b'speechbrain\n')
    f.write(b'openwakeword\n')
    f.write(b'pyttsx3\n')
    f.write(b'pycaw; sys_platform == "win32"\n')
    f.write(b'comtypes; sys_platform == "win32"\n')
    f.write(b'pywin32; sys_platform == "win32"\n')
    f.write(b'pypdf>=4\n')
    f.write(b'python-docx>=1.1\n')
    f.write(b'boto3>=1.28\n')
    f.write(b'\n')
    f.write(b'# DEVELOPMENT / TEST DEPENDENCIES\n')
    f.write(b'pytest>=8\n')
    f.write(b'pytest-cov>=5\n')
    f.write(b'pytest-asyncio>=0.23\n')
    f.write(b'httpx==0.28.1\n')
    f.write(b'ruff\n')
    f.write(b'black\n')
    f.write(b'\n')
    f.write(b'# SECTION: except-core-host\n')
    f.write(b'# =============================================================================\n')
    f.write(b'# CORE RUNTIME - EXCEPT CORE-HOST (excludes PyYAML and fastapi stack)\n')
    f.write(b'platformdirs>=4\n')
    f.write(b'python-dotenv>=1.0\n')
    f.write(b'sympy>=1.13\n')
    f.write(b'requests>=2.31\n')
    f.write(b'windows-curses>=2.3; sys_platform == "win32"\n')
    f.write(b'# PyYAML>=6.0  <-- EXCLUDED (core-host)\n')
    f.write(b'# fastapi==0.141.1  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# uvicorn[standard]==0.52.4  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# sqlalchemy==2.0.52  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# psycopg[binary]==3.3.4  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# pydantic==2.13.5  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# pydantic-settings==2.15.0  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'# python-multipart==0.0.32  <-- EXCLUDED (core-host/RESCS)\n')
    f.write(b'\n')
    f.write(b'# EXTRAS - All optional (same as all)\n')
    f.write(b'textual>=0.70\n')
    f.write(b'textual-dev>=0.70\n')
    f.write(b'numpy\n')
    f.write(b'scipy\n')
    f.write(b'sounddevice\n')
    f.write(b'soundfile\n')
    f.write(b'silero-vad\n')
    f.write(b'faster-whisper\n')
    f.write(b'torch\n')
    f.write(b'torchaudio\n')
    f.write(b'speechbrain\n')
    f.write(b'openwakeword\n')
    f.write(b'pyttsx3\n')
    f.write(b'pycaw; sys_platform == "win32"\n')
    f.write(b'comtypes; sys_platform == "win32"\n')
    f.write(b'pywin32; sys_platform == "win32"\n')
    f.write(b'pypdf>=4\n')
    f.write(b'python-docx>=1.1\n')
    f.write(b'boto3>=1.28\n')
    f.write(b'\n')
    f.write(b'# DEVELOPMENT / TEST DEPENDENCIES\n')
    f.write(b'pytest>=8\n')
    f.write(b'pytest-cov>=5\n')
    f.write(b'pytest-asyncio>=0.23\n')
    f.write(b'httpx==0.28.1\n')
    f.write(b'ruff\n')
    f.write(b'black\n')
    f.write(b'\n')
    f.write(b'# SECTION: except-core-client\n')
    f.write(b'# =============================================================================\n')
    f.write(b'# CORE RUNTIME - EXCEPT CORE-CLIENT (core-client has no direct deps, same as all)\n')
    f.write(b'platformdirs>=4\n')
    f.write(b'python-dotenv>=1.0\n')
    f.write(b'sympy>=1.13\n')
    f.write(b'requests>=2.31\n')
    f.write(b'windows-curses>=2.3; sys_platform == "win32"\n')
    f.write(b'PyYAML>=6.0\n')
    f.write(b'fastapi==0.141.1\n')
    f.write(b'uvicorn[standard]==0.52.4\n')
    f.write(b'sqlalchemy==2.0.52\n')
    f.write(b'psycopg[binary]==3.3.4\n')
    f.write(b'pydantic==2.13.5\n')
    f.write(b'pydantic-settings==2.15.0\n')
    f.write(b'python-multipart==0.0.32\n')
    f.write(b'\n')
    f.write(b'# EXTRAS - All optional (same as all)\n')
    f.write(b'textual>=0.70\n')
    f.write(b'textual-dev>=0.70\n')
    f.write(b'numpy\n')
    f.write(b'scipy\n')
    f.write(b'sounddevice\n')
    f.write(b'soundfile\n')
    f.write(b'silero-vad\n')
    f.write(b'faster-whisper\n')
    f.write(b'torch\n')
    f.write(b'torchaudio\n')
    f.write(b'speechbrain\n')
    f.write(b'openwakeword\n')
    f.write(b'pyttsx3\n')
    f.write(b'pycaw; sys_platform == "win32"\n')
    f.write(b'comtypes; sys_platform == "win32"\n')
    f.write(b'pywin32; sys_platform == "win32"\n')
    f.write(b'pypdf>=4\n')
    f.write(b'python-docx>=1.1\n')
    f.write(b'boto3>=1.28\n')
    f.write(b'\n')
    f.write(b'# DEVELOPMENT / TEST DEPENDENCIES\n')
    f.write(b'pytest>=8\n')
    f.write(b'pytest-cov>=5\n')
    f.write(b'pytest-asyncio>=0.23\n')
    f.write(b'httpx==0.28.1\n')
    f.write(b'ruff\n')
    f.write(b'black\n')
    print('File written successfully')